scripts/setup-stackinator
- work around `spack find ...` bug when using `develop`/`v0.20` of spack.
- fix bwrap issue with broken symlinks
=> update stackinator version

recipes/mch/a100/config.yaml, recipes/mch/a100/environments.yaml, recipes/mch/a100/repo/packages/nvhpc/package.py, recipes/mch/readme.md
=> MCH manali v5 software stack

docs/uenv-qe.md, mkdocs.yml, recipes/quantumespresso/a100/compilers.yaml, recipes/quantumespresso/a100/config.yaml, recipes/quantumespresso/a100/environments.yaml, recipes/quantumespresso/a100/modules.yaml, recipes/quantumespresso/ci.yml
=> Add Quantumespresso

scripts/setup-stackinator, stack-build
=> Add support for Stackinator --develop

ci/config/configuration.py, recipes/mch/v6/environments.yaml, recipes/prgenv-gnu/23.11/a100/environments.yaml, scripts/setup-oras, scripts/setup-stackinator
=> split cray packages

recipes/wcp/icon/v1/a100/compilers.yaml, recipes/wcp/icon/v1/a100/environments.yaml, recipes/wcp/icon/v1/gh200/environments.yaml
=> update wcp icon recipe for a100

config.yaml
added gh200 todi, and updated the uenv for
* arbor, prgenv-gnu, netcdf
=> Add cluster configuration for todi

mkdocs.yml
* Add NAMD to documentation, following #85
* Use official names for packages in index
=> Add NAMD to documentation

config.yaml, recipes/prgenv-gnu/24.7/mc/compilers.yaml, recipes/prgenv-gnu/24.7/mc/config.yaml, recipes/prgenv-gnu/24.7/mc/environments.yaml, recipes/prgenv-gnu/24.7/mc/extra/reframe.yaml, recipes/prgenv-gnu/24.7/mc/modules.yaml, scripts/setup-stackinator
For testing the latest version of stackinator
=> add prgenv-gnu/24.7 for eiger

recipes/quantumespresso/v7.3.1/gh200/environments.yaml
upgrade the QE env to `cray-mpich@8.1.30`
=> update cray-mpich to 8.1.30

recipes/prgenv-gnu/24.7/gh200/extra/reframe.yaml, recipes/prgenv-gnu/24.7/mc/extra/reframe.yaml
=> update reframe.yaml of prgenv-gnu/24.7

ci/config/configuration.py, config.yaml
uses a temporary runner that will be replaced with f7t
=> add daint.alps configuration

config.yaml, docs/uenv-qe.md, recipes/quantumespresso/v7.3.1/gh200/environments.yaml
@abussy reported `uenv start cp2k/2024.2:v1`  contains cp2k@2024.1 on eiger
=> Fix cp2k version

docs/userlab-2024-tutorial.md, mkdocs.yml
tutorial notes for the CSCS user lab day 2024
=> Userday 2024

docs/pkg-reframe.md
A few fixes and suggestions to the ReFrame documentation.
=> Fixes and suggestions for ReFrame documentation

docs/uenv-linaro-forge.md
=> Remove reference to old Linaro MAP image

recipes/namd/3.0/gh200/extra/reframe.yaml
https://github.com/eth-cscs/cscs-reframe-tests/pull/245
=> NAMD ReFrame configuration

config.yaml, recipes/vasp/v6.5.0/gh200/compilers.yaml, recipes/vasp/v6.5.0/gh200/config.yaml, recipes/vasp/v6.5.0/gh200/environments.yaml, recipes/vasp/v6.5.0/gh200/extra/reframe.yaml, recipes/vasp/v6.5.0/gh200/modules.yaml, recipes/vasp/v6.5.0/gh200/pre-install, recipes/vasp/v6.5.0/gh200/repo/packages/libxc/0001-Bugfix-avoid-implicit-pointer-cast-to-make-libxc-com.patch, recipes/vasp/v6.5.0/gh200/repo/packages/libxc/0002-Mark-xc_erfcx-a-GPU_FUNCTION.patch, recipes/vasp/v6.5.0/gh200/repo/packages/libxc/nvhpc-configure.patch, recipes/vasp/v6.5.0/gh200/repo/packages/libxc/nvhpc-libtool.patch, recipes/vasp/v6.5.0/gh200/repo/packages/libxc/package.py, recipes/vasp/v6.5.0/gh200/repo/packages/vasp/mpix_cuda.patch, recipes/vasp/v6.5.0/gh200/repo/packages/vasp/package.py
Add VASP version 6.5.0. Verification tests all passed.
=> VASP v6.5.0 for gh200

.github/CODEOWNERS
@abussy and @nickjbrowning don't currently have write access to this repository.
=> Add sciapps codeowners

recipes/prgenv-nvfortran/24.11/gh200/extra/reframe.yaml
Adding correct view to reframe.yaml:
```
views:
spack: configure spack upstream
nvfort:
modules: activate modules
```
=> Update reframe activation
