stack-build
Replace `--fail` with `--fail-with-body`, to see what we received from the server in case of HTTP-4XX response codes.
Add `--retry-connrefused`, which is not an HTTP resopnse code to retry, but rather a glitch in connecting to the remote server.
=> print body on HTTP-errors. Also retry connection refused errors

stack-build
It seems that there are trailing spaces after the HTTP response code, ignore all of them when matching for the expected string
=> ignore trailing spaces when looking for http response code 2XX

ci/config/templates/pipeline.yml
increase gitlab job timelimits to a high ceiling so that SLURM controls job duration
=> Increase build and test job timeout

scripts/setup-stackinator
It should fix build failures in #67 (different SHA for `cray-mpich` introduced in https://github.com/eth-cscs/stackinator/pull/158).
=> Update Stackinator version

scripts/setup-oras
It will become mandatory soon to add `job_id`, when requesting credentials
=> Include job_id when requesting credentials

config.yaml, docs/uenv-cp2k.md, recipes/cp2k/2024.1/gh200/compilers.yaml, recipes/cp2k/2024.1/gh200/config.yaml, recipes/cp2k/2024.1/gh200/environments.yaml, recipes/cp2k/2024.1/gh200/modules.yaml, recipes/cp2k/2024.1/gh200/repo/packages/cosma/fj-ssl2.patch, recipes/cp2k/2024.1/gh200/repo/packages/cosma/mpi-view.patch, recipes/cp2k/2024.1/gh200/repo/packages/cosma/package.py, recipes/cp2k/2024.1/gh200/repo/packages/costa/mpi-view.patch, recipes/cp2k/2024.1/gh200/repo/packages/costa/package.py, recipes/cp2k/2024.1/gh200/repo/packages/elpa/package.py
=> CP2K 2024.1 (GH200)

docs/uenv-compilation-spack.md, mkdocs.yml
Draft for a documentation page explaining how to use user environments as upstream Spack instances. I think many people at CSCS use this or a similar workflow for development, so it might be useful for the end users too.
Feedback and suggestions on how to improve it very welcome! This is a rough initial draft to get the conversation started.
=> Document how to use uenvs as upstream Spack instances

docs/uenv-cp2k.md
Add missing `\` for the copy-paste aficionados.
=> Small fix to CP2K documentation

recipes/prgenv-gnu/24.7/gh200/environments.yaml, recipes/prgenv-gnu/24.7/mc/environments.yaml
The +hl variant enables the "high level" interface for hdf5, which is required by some packages.
=> prgenv-gnu: add +hl variant to hdf5

docs/uenv-namd.md
Try to make it clearer that the user should specify the UENV name. Hopefully avoids tickets from copy-paste as [SD-61793](https://jira.cscs.ch/browse/SD-61793).
=> Small fix to NAMD documentation

config.yaml, docs/uenv-namd.md, recipes/namd/3.0/gh200/compilers.yaml, recipes/namd/3.0/gh200/config.yaml, recipes/namd/3.0/gh200/environments.yaml, recipes/namd/3.0/gh200/modules.yaml, recipes/namd/3.0/gh200/pre-install, recipes/namd/3.0/gh200/repo/packages/charmpp/charm_6.7.1_aocc.patch, recipes/namd/3.0/gh200/repo/packages/charmpp/charm_6.8.2_aocc.patch, recipes/namd/3.0/gh200/repo/packages/charmpp/fj.patch, recipes/namd/3.0/gh200/repo/packages/charmpp/mpi.patch, recipes/namd/3.0/gh200/repo/packages/charmpp/nvhpc.patch, recipes/namd/3.0/gh200/repo/packages/charmpp/ofi-crayshasta-arm-7.0.0.patch, recipes/namd/3.0/gh200/repo/packages/charmpp/ofi-crayshasta-arm-8.0.0.patch, recipes/namd/3.0/gh200/repo/packages/charmpp/package.py, recipes/namd/3.0/gh200/repo/packages/charmpp/strictpass.patch, recipes/namd/3.0/gh200/repo/packages/namd/inherited-member-2.13.patch, recipes/namd/3.0/gh200/repo/packages/namd/inherited-member-2.14.patch, recipes/namd/3.0/gh200/repo/packages/namd/namd-python38.patch, recipes/namd/3.0/gh200/repo/packages/namd/package.py
Add NAMD `3.0`, the fist official release of `3.x`, using Charm++ `8.0.0` as backend.
This is still a single-node build, but the name of the views have been changed in preparation for a multi-node build: `namd-single-node` and `develop-single-node`.
Installation instructions have been updated to use Charm++ 8.0.0, bundled with NAMD 3.0. Additionally, an optional section on how to build a CPU-only version had been added. Apparently for cpHMD simulations both a CPU and GPU version are needed at the same time.
=> NAMD 3.0 (GH200)

docs/uenv-namd.md, recipes/namd/3.0/gh200/compilers.yaml, recipes/namd/3.0/gh200/environments.yaml
* GPU-resident mode requires `tcl@8.6` (see 3.0 release notes)
* This was not the case/not documented in the `3.0b6` release
* ARM64 arch files still hard-code `-ltcl8.5` so the build instructions have been updated accordingly
* Provide multi-node build with MPI backend
* Charm++ MPI backend was not possible to use with `3.0b6` but it is now available
* Added instructions to build the multi-node version (with Charm++ MPI backend) from source
=> NAMD 3.0 (GH200): use tcl@8.6 and add multi-node build (with MPI) 

ci/config/configuration.py
The firecrest gitlab runner has renamed the variable `MODE` to `CSCS_RUNNER_MODE`.
Currently the runner has a fallback to the old variable name, but this will be removed eventually, and then pipelines in this repository will fail.
=> adapt to variable rename MODE --> CSCS_RUNNER_MODE

recipes/cp2k/2024.3/gh200/extra/reframe.yaml, recipes/cp2k/2024.3/gh200/repo/packages/cp2k/d4-dispersion-bugfix-2024.3.patch, recipes/cp2k/2024.3/gh200/repo/packages/cp2k/package.py, recipes/cp2k/2024.3/mc/repo/packages/cp2k/d4-dispersion-bugfix-2024.3.patch, recipes/cp2k/2024.3/mc/repo/packages/cp2k/package.py
Add `reframe.yaml`, and patch version 2024.3 with https://github.com/cp2k/cp2k/issues/3688.
=> CP2K reframe config and patch for 2024.3

docs/tutorial-spack.md
@finkandreas pointed out that git clone -b works only for branches, not commits.
~Here is a handy oneliner to workaround this limitation~
=> replace git clone by source code archive URLs

recipes/prgenv-gnu/24.11/a100/environments.yaml, recipes/prgenv-gnu/24.11/gh200/environments.yaml, recipes/prgenv-gnu/24.11/mc/environments.yaml
... because it is often the only thing stopping users from using the prgenv-gny uenv
=> add netcdf to prgenv-gnu/24.11

config.yaml, recipes/editors/25.3/compilers.yaml, recipes/editors/25.3/config.yaml, recipes/editors/25.3/environments.yaml, recipes/editors/25.3/modules.yaml, recipes/editors/25.3/repo/packages/nnn/package.py
`nnn` (filemanager) has disappeared from eiger. Also add py-ranger-fm (another filemanager) to the image.
=> editors v25.3, incl nnn, py-ranger-fm

recipes/prgenv-gnu/24.11/gh200/extra/reframe.yaml
[prgenv-gnu/24.11/gh200/extra/reframe.yaml](https://github.com/eth-cscs/alps-uenv/blob/main/recipes/prgenv-gnu/24.11/gh200/extra/reframe.yaml#L11) sets the default view to:
```
views:
- develop 
```
but the views are: 
```
views:
spack: configure spack upstream
modules: activate modules
default:
```
This pr updates reframe.yaml
=> update prgenv-gnu view in reframe.yaml

recipes/cp2k/2025.1/gh200/environments.yaml, recipes/cp2k/2025.1/gh200/extra/reframe.yaml, recipes/cp2k/2025.1/gh200/modules.yaml, recipes/cp2k/2025.1/mc/environments.yaml, recipes/cp2k/2025.1/mc/modules.yaml
Fix some issues with CP2K+DLAF by separating the `cp2k+dlaf` integration in a standalone view.
=> CP2K 2025.1

recipes/q-e-sirius/v1.0.1/gh200/environments.yaml, recipes/q-e-sirius/v1.0.1/mc/environments.yaml, recipes/q-e-sirius/v1.0.1/mc/extra/reframe.yaml, recipes/q-e-sirius/v1.0.1/repo/packages/nlcglib/package.py, recipes/q-e-sirius/v1.0.1/repo/packages/sirius/package.py
Update `sirius` `7.7.1` -> `7.8.0`, new nlcglib version.
To be deployed as `q-e-sirius/1.0.1:v2`.
=> sirius 7.8 / nlcglib 1.3

recipes/prgenv-gnu/25.6/gh200/modules.yaml, recipes/prgenv-gnu/25.6/mc/modules.yaml
When going from prgenv-gnu/24.11 to 25.6, I blindly updated the `exclude` field for modules to exclude the newer system compiler. After the bootstrapping was removed, this excludes the actual compiler we want to expose as a module. I think we can get away without excluding any specific modules. Only the correct `gcc` is considered at least in the case of prgenv-gnu/25.6 even when the exclude field is empty.
=> Don't exclude gcc module in `prgenv-gnu`

recipes/q-e-sirius/v1.0.1/gh200/environments.yaml, recipes/q-e-sirius/v1.0.1/gh200/extra/reframe.yaml, recipes/quantumespresso/v7.4.1/gh200/extra/reframe.yaml
I noticed the qe (quantumespresso and q-e-sirius) uenvs advertise the `cuda` reframe feature, but they don't load cuda (or nvhpc) in the activation part. This means that generic reframe tests that check for the cuda feature (and expect e.g. nvcc to be available) will fail.
I'm proposing to add cuda (nvhpc for quantumespresso, because that's in the root specs; maybe cuda is better to load?) so that the cuda feature can correctly be relied on.
Alternatives:
- don't advertise the cuda feature at all (but this feels wrong, because I guess reframe tests might want to check for e.g. `+qe +cuda` to determine if cuda features are enabled for qe)
- load the default view
I'm not planning to rebuild the uenvs now, but want to update these for the next time the uenvs get updated.
=> Make sure qe reframe activations have cuda available

recipes/vasp/v6.5.1/gh200/environments.yaml
Fix missing module files by changing compiler spec for nvpl packages.
Depends on https://github.com/eth-cscs/cscs-reframe-tests/pull/415 to run reframe tests.
=> VASP: Fix missing nvpl module files
